---
- name: Setup .gitconfig
  copy:
    src: "{{ home_dir }}/dotfiles/.gitconfig"
    dest: "{{ home_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags:
    - git

- name: Setup .gitmessage
  copy:
    src: "{{ home_dir }}/dotfiles/.gitmessage"
    dest: "{{ home_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
