---
- hosts: localhost
  become: yes
  vars:
    user: "suinming"
    home_dir: "/home/suinming"
    dotfiles_repo: "git@github.com:suinming/dotfiles.git"
    space_mono_nerd_font_link: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/SpaceMono.zip

  tasks:
    - name: Ensure font directory exists
      file:
        path: /usr/local/share/fonts/nerd-fonts
        state: directory
        mode: '0755'
      tags:
        - nerd-font

    - name: Download SpaceMono Nerd Font
      get_url:
        url: "{{ space_mono_nerd_font_link }}"
        dest: /tmp/SpaceMono.zip
      tags:
        - nerd-font

    - name: Unzip SpaceMono Nerd Font
      unarchive:
        src: /tmp/SpaceMono.zip
        dest: /usr/local/share/fonts/nerd-fonts
        remote_src: yes
      tags:
        - nerd-font

    - name: Clone Neovim repository
      git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ home_dir }}/neovim"
        version: stable
      tags:
        - neovim

    - name: Build Neovim
      command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Install Neovim
      command:
        cmd: sudo make install
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Configure Neovim
      copy:
        src: "{{ home_dir }}/dotfiles/.config/nvim"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - neovim

    - name: Get starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'
      register: starship_installation_script
      tags:
        - starship
     
    - name: Install starship with installation script
      become: true
      ansible.builtin.shell:
        cmd: /tmp/starship_install.sh --yes
        executable: /bin/sh
      when: starship_installation_script.changed
      tags:
        - starship

    - name: Configure Starship
      copy:
        src: "{{ home_dir }}/dotfiles/.config/starship.toml"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - starship

    - name: Add the Wezterm GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
      args:
        creates: /etc/apt/keyrings/wezterm-fury.gpg
      tags:
        - wezterm 

    - name: Add the Wezterm APT repository
      ansible.builtin.shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
      args:
        creates: /etc/apt/sources.list.d/wezterm.list
      tags:
        - wezterm 

    - name: Update APT repositories
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - wezterm 

    - name: Install Wezterm
      ansible.builtin.apt:
        name: wezterm
        state: present
      tags:
        - wezterm 

    - name: Copy wezterm.lua to .config/wezterm/wezterm.lua 
      copy:
        src: "{{ home_dir }}/dotfiles/.config/wezterm"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      tags:
        - wezterm 

    - name: Clone oh-my-tmux repository
      git:
        repo: 'https://github.com/gpakosz/.tmux.git'
        dest: '{{ home_dir }}/oh-my-tmux'
        update: yes
      tags:
        - tmux

    - name: Ensure ~/.config/tmux directory exists
      file:
        path: "{{ home_dir }}/.config/tmux"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      tags:
        - tmux

    - name: Create symlink for .tmux.conf
      file:
        src: "{{ home_dir }}/oh-my-tmux/.tmux.conf"
        dest: "{{ home_dir }}/.config/tmux/tmux.conf"
        state: link
        owner: "{{ user }}"
        group: "{{ user }}"
      tags:
        - tmux

    - name: Copy .tmux.conf.local to ~/.config/tmux
      copy:
        src: "{{ home_dir }}/dotfiles/.config/tmux/.tmux.conf.local"
        dest: "{{ home_dir }}/.config/tmux/tmux.conf.local"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      tags:
        - tmux

    - name: Create .zprofile file with export PATH
      copy:
        dest: "{{ home_dir }}/.zprofile"
        content: |
          export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
        mode: '0644'
        owner: "{{ user }}"
        group: "{{ user }}"
      tags:
        - tmux-session

    - name: Install nvm
      become: no
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags:
        - nvm

    - name: Copy the i3 config file
      copy:
        src: "{{ home_dir }}/dotfiles/.config/i3"
        dest: "{{ home_dir }}/.config"
        mode: '0644'
      tags:
        - i3 

    - name: Copy the zshrc config file
      copy:
        src: "{{ home_dir }}/dotfiles/.zshrc"
        dest: "{{ home_dir }}"
        mode: '0644'
      tags:
        - zsh 

    - name: Change user shell to zsh 
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      tags:
        - zsh 

    - name: Get zoxide install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: "/tmp/zoxide_install.sh"
        mode: '0755'
      tags:
        - zoxide 

    - name: Install zoxide with installation script
      become: true
      script: "/tmp/zoxide_install.sh"
      tags:
        - zoxide 
