---
- hosts: localhost
  become: yes
  vars:
    user: "suinming"
    home_dir: "/home/suinming"
    dotfiles_repo: "git@github.com:suinming/dotfiles.git"
    space_mono_nerd_font_link: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/SpaceMono.zip

  tasks:
    # 2. Install nvm (user environment setup)
    - name: Install nvm
      become: no
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags:
        - nvm

    # 3. Configure Zsh and make it the default shell
    - name: Copy the zshrc config file
      copy:
        src: "{{ home_dir }}/dotfiles/.zshrc"
        dest: "{{ home_dir }}"
        mode: '0644'
      tags:
        - zsh

    - name: Change user shell to Zsh
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      tags:
        - zsh

    # install neovim
    - name: Build Neovim
      command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Install Neovim
      command:
        cmd: sudo make install
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Configure Neovim
      copy:
        src: "{{ home_dir }}/dotfiles/.config/nvim"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - neovim

    # 6. Install and configure Starship prompt
    - name: Get starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'
      register: starship_installation_script
      tags:
        - starship

    - name: Install starship with installation script
      become: true
      ansible.builtin.shell:
        cmd: /tmp/starship_install.sh --yes
        executable: /bin/sh
      when: starship_installation_script.changed
      tags:
        - starship

    - name: Configure Starship
      copy:
        src: "{{ home_dir }}/dotfiles/.config/starship.toml"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - starship

    # 7. Install and configure Wezterm
    - name: Add the Wezterm GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
      args:
        creates: /etc/apt/keyrings/wezterm-fury.gpg
      tags:
        - wezterm

    - name: Add the Wezterm APT repository
      ansible.builtin.shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
      args:
        creates: /etc/apt/sources.list.d/wezterm.list
      tags:
        - wezterm

    - name: Update APT repositories
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - wezterm

    - name: Install Wezterm
      ansible.builtin.apt:
        name: wezterm
        state: present
      tags:
        - wezterm

    - name: Copy wezterm.lua to .config/wezterm/wezterm.lua
      copy:
        src: "{{ home_dir }}/dotfiles/.config/wezterm"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      tags:
        - wezterm

    - name: Copy the i3 config file
      copy:
        src: "{{ home_dir }}/dotfiles/.config/i3"
        dest: "{{ home_dir }}/.config"
        mode: '0644'
      tags:
        - i3 
