---
- hosts: localhost
  become: yes
  vars:
    user: suinming
    dotfiles_repo: git@github.com:suinming/dotfiles.git
    ssh_key: .ssh/id_ed25519
    space_mono_nerd_font_link: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/SpaceMono.zip

  tasks:
    - name: Ensure font directory exists
      file:
        path: /usr/local/share/fonts/nerd-fonts
        state: directory
        mode: '0755'
      tags:
        - nerd-font

    - name: Download SpaceMono Nerd Font
      get_url:
        url: "{{ space_mono_nerd_font_link }}"
        dest: /tmp/SpaceMono.zip
      tags:
        - nerd-font

    - name: Unzip SpaceMono Nerd Font
      unarchive:
        src: /tmp/SpaceMono.zip
        dest: /usr/local/share/fonts/nerd-fonts
        remote_src: yes
      tags:
        - nerd-font

    - name: Clone Neovim repository
      git:
        repo: https://github.com/neovim/neovim.git
        dest: "/home/{{ user }}/neovim"
        version: stable
      tags:
        - neovim

    - name: Build Neovim
      command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: "/home/{{ user }}/neovim"
      tags:
        - neovim

    - name: Install Neovim
      command:
        cmd: sudo make install
        chdir: "/home/{{ user }}/neovim"
      tags:
        - neovim

    - name: Configure Neovim
      copy:
        src: "/home/{{ user }}/dotfiles/.config/nvim"
        dest: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - neovim

    - name: Install Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/{{ user }}/.oh-my-zsh
        depth: 1
      tags:
        - oh-my-zsh 

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1
      tags:
        - oh-my-zsh 

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
      tags:
        - oh-my-zsh 

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1
      tags:
        - oh-my-zsh 

    - name: Get starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'
      register: starship_installation_script
      when: ansible_os_family != 'Archlinux'
      tags:
        - starship
     
    - name: Install starship with installation script
      become: true
      ansible.builtin.shell:
        cmd: /tmp/starship_install.sh --yes
        executable: /bin/sh
      when: ansible_os_family != 'Archlinux' and starship_installation_script.changed
      tags:
        - starship

    - name: Configure Starship
      copy:
        src: "/home/{{ user }}/dotfiles/.config/starship.toml"
        dest: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - starship

    - name: Add the Wezterm GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
      args:
        creates: /etc/apt/keyrings/wezterm-fury.gpg
      tags:
        - wezterm 

    - name: Add the Wezterm APT repository
      ansible.builtin.shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
      args:
        creates: /etc/apt/sources.list.d/wezterm.list
      tags:
        - wezterm 

    - name: Update APT repositories
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - wezterm 

    - name: Install Wezterm
      ansible.builtin.apt:
        name: wezterm
        state: present
      tags:
        - wezterm 

    - name: Copy wezterm.lua to .config/wezterm/wezterm.lua 
      copy:
        src: "/home/{{ user }}/dotfiles/.config/wezterm"
        dest: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      tags:
        - wezterm 

    - name: Clone oh-my-tmux repository
      git:
        repo: 'https://github.com/gpakosz/.tmux.git'
        dest: '/home/{{ user }}/oh-my-tmux'
        update: yes
      tags:
        - tmux

    - name: Ensure ~/.config/tmux directory exists
      file:
        path: "/home/{{ user }}/.config/tmux"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      tags:
        - tmux

    - name: Create symlink for .tmux.conf
      file:
        src: "/home/{{ user }}/oh-my-tmux/.tmux.conf"
        dest: "/home/{{ user }}/.config/tmux/tmux.conf"
        state: link
        owner: "{{ user }}"
        group: "{{ user }}"
      tags:
        - tmux

    - name: Copy .tmux.conf.local to ~/.config/tmux
      copy:
        src: "/home/{{ user }}/dotfiles/.config/tmux/.tmux.conf.local"
        dest: "/home/{{ user }}/.config/tmux/tmux.conf.local"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      tags:
        - tmux

    - name: Create .zprofile file with export PATH
      copy:
        dest: "/home/{{ user }}/.zprofile"
        content: |
          export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
        mode: '0644'
        owner: "{{ user }}"
        group: "{{ user }}"
      tags:
        - tmux-session

    - name: Install nvm
      become: no
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags:
        - nvm

    - name: Copy the i3 config file
      copy:
        src: "/home/{{ user }}/dotfiles/i3"
        dest: "/home/{{ user }}/.config/i3"
        mode: '0644'
      tags:
        - i3 

    - name: Change user shell to zsh 
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      tags:
        - zsh 
