---
- name: Execute Tasks In Ubuntu24.04
  hosts: localhost
  tasks:
    - name: Apt update and install packages
      import_tasks: tasks/ubuntu24.04/apt_update_install.yml

    - name: Pull dotfiles
      import_tasks: tasks/ubuntu24.04/pull_dotfiles.yml

    - name: Pull digitalMind, cht, myscripts
      import_tasks: tasks/ubuntu24.04/pull_repos.yml

    - name: Zoxide
      import_tasks: tasks/ubuntu24.04/zoxide.yml

    - name: Neovim
      import_tasks: tasks/ubuntu24.04/nvim.yml

    - name: Spacemono nerd font
      import_tasks: tasks/ubuntu24.04/spacemono_nerd_font.yml

    - name: Nvm
      import_tasks: tasks/ubuntu24.04/nvm.yml

    - name: Starship
      import_tasks: tasks/ubuntu24.04/starship.yml

    - name: Git config
      import_tasks: tasks/ubuntu24.04/git.yml

    - name: Zsh
      import_tasks: tasks/ubuntu24.04/zsh.yml

    - name: Wezterm
      import_tasks: tasks/ubuntu24.04/wezterm.yml

    - name: Tmux
      import_tasks: tasks/ubuntu24.04/tmux.yml

    - name: Go
      import_tasks: tasks/ubuntu24.04/go.yml

    - name: Rust
      import_tasks: tasks/ubuntu24.04/rust.yml

    - name: Sesh
      import_tasks: tasks/ubuntu24.04/sesh.yml

    - name: Lsp
      import_tasks: tasks/ubuntu24.04/lsp.yml

    - name: Linter
      import_tasks: tasks/ubuntu24.04/linter.yml

    - name: Formatter
      import_tasks: tasks/ubuntu24.04/formatter.yml

    - name: I3 window manager
      import_tasks: tasks/ubuntu24.04/i3.yml

    - name: Rofi
      import_tasks: tasks/ubuntu24.04/rofi.yml
