---
- name: Execute Tasks 
  hosts: localhost
  tasks:
    - name: Apt update and install packages 
      import_tasks: tasks/apt_update_install.yml

    - name: Pull dotfiles 
      import_tasks: tasks/pull_dotfiles.yml 

    - name: Zoxide 
      import_tasks: tasks/zoxide.yml 

    - name: Neovim
      import_tasks: tasks/nvim.yml 

    - name: Spacemono nerd font 
      import_tasks: tasks/spacemono_nerd_font.yml 

    - name: Nvm 
      import_tasks: tasks/nvm.yml 

    - name: Starship
      import_tasks: tasks/starship.yml 

    - name: Git config 
      import_tasks: tasks/git.yml 

    - name: Zsh
      import_tasks: tasks/zsh.yml

    - name: Wezterm
      import_tasks: tasks/wezterm.yml

    - name: Tmux 
      import_tasks: tasks/tmux.yml

    - name: Go 
      import_tasks: tasks/go.yml

    - name: Sesh
      import_tasks: tasks/sesh.yml

    - name: I3 window manager
      import_tasks: tasks/i3.yml
