---
- hosts: localhost
  become: yes
  vars:
    user: "suinming"
    home_dir: "/home/suinming"
    dotfiles_repo: "git@github.com:suinming/dotfiles-kickstart-win.git"
    nvim_repo: "https://github.com/neovim/neovim.git"
    zsh_autosuggestions_repo: "git@github.com:zsh-users/zsh-autosuggestions.git"
    zoxide_install_script_link: "https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh"
    starship_install_script_link: "https://starship.rs/install.sh"
    space_mono_nerd_font_link: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/SpaceMono.zip
    ssh_key: "/home/suinming/.ssh/id_ed25519"
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Install updates (WSL Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install system packages
      apt:
        name:
          - git
          - bat
          - zsh
          - ripgrep
          - fzf
          - eza
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - python3
          - python3-pip
        state: latest

    - name: Ensure .config directory exists
      file:
        path: "{{ home_dir }}/.config"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Pull dotfiles from GitHub repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ home_dir }}/dotfiles"
        accept_hostkey: yes
        key_file: "{{ ssh_key }}"
        force: yes
      delegate_to: localhost
      run_once: true
      tags:
        - git

    - name: Pull zsh-autosuggestions from GitHub repository
      git:
        repo: "{{ zsh_autosuggestions_repo }}"
        dest: "{{ home_dir }}/.zsh/zsh-autosuggestions"
        accept_hostkey: yes
        key_file: "{{ ssh_key }}"
        force: yes
      delegate_to: localhost
      run_once: true
      tags:
        - git

    - name: Pull Neovim from GitHub repository
      git:
        repo: "{{ nvim_repo }}" 
        dest: "{{ home_dir }}/neovim"
        version: stable
      tags:
        - neovim

    - name: Get zoxide install script
      get_url:
        url: "{{ zoxide_install_script_link }}"
        dest: "/tmp/zoxide_install.sh"
        mode: '0755'
      tags:
        - zoxide

    - name: Install zoxide with installation script
      become: false
      shell: "/tmp/zoxide_install.sh"
      args:
        executable: /bin/bash
      tags:
        - zoxide

    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags:
        - nvm

    - name: Get starship install script
      get_url:
        url: "{{ starship_install_script_link }}" 
        dest: /tmp/starship_install.sh
        mode: '0755'
      tags:
        - starship

    - name: Install starship with installation script
      shell:
        cmd: /tmp/starship_install.sh --yes
        executable: /bin/sh
      tags:
        - starship

    - name: Configure Starship
      copy:
        src: "{{ home_dir }}/dotfiles/.config/starship.toml"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - starship

    - name: Setup .gitconfig
      copy:
        src: "{{ home_dir }}/dotfiles/.gitconfig"
        dest: "{{ home_dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      tags:
        - git

    - name: Setup .gitmessage
      copy:
        src: "{{ home_dir }}/dotfiles/.gitmessage"
        dest: "{{ home_dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      tags:
        - git

    - name: Copy the zshrc config file
      copy:
        src: "{{ home_dir }}/dotfiles/.zshrc"
        dest: "{{ home_dir }}"
        mode: '0644'
      tags:
        - zsh

    - name: Change user shell to Zsh
      user:
        name: "{{ user }}"
        shell: /bin/zsh
      tags:
        - zsh

    - name: Build Neovim
      command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Install Neovim locally (no sudo for WSL)
      command:
        cmd: make install
        chdir: "{{ home_dir }}/neovim"
      tags:
        - neovim

    - name: Ensure Neovim config directory exists
      file:
        path: "{{ home_dir }}/.config/nvim"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      tags:
        - neovim

    - name: Configure Neovim
      copy:
        src: "{{ home_dir }}/dotfiles/.config/nvim"
        dest: "{{ home_dir }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
      tags:
        - neovim

    - name: Ensure required directories for Neovim exist
      file:
        path: "{{ ansible_user_dir }}/.local/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - ""
        - "share"
        - "state"
        - "cache"
      tags:
        - neovim

    - name: Ensure Neovim config directory exists
      file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      tags:
        - neovim

    - name: Fix permissions recursively for Neovim directories
      command: >
        chmod -R 0755 {{ item }}
      loop:
        - "{{ ansible_user_dir }}/.local"
        - "{{ ansible_user_dir }}/.config/nvim"
      tags:
        - neovim

    - name: Fix ownership recursively for Neovim directories
      command: >
        chown -R {{ ansible_user }}:{{ ansible_user }} {{ item }}
      loop:
        - "{{ ansible_user_dir }}/.local"
        - "{{ ansible_user_dir }}/.config/nvim"
      tags:
        - neovim

