---
- name: Install updates (Ubuntu)
  become: true
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name:
      - git
      - bat
      - zsh
      - ripgrep
      - fzf
      - eza
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - python3
      - python3-pip
      - i3
      - i3blocks
    state: latest
