---
- name: Ensure font directory exists
  become: true
  file:
    path: /usr/local/share/fonts/nerd-fonts
    state: directory
    mode: '0755'

- name: Download SpaceMono Nerd Font
  become: true
  get_url:
    url: "{{ space_mono_nerd_font_link }}"
    dest: /tmp/SpaceMono.zip

- name: Unzip SpaceMono Nerd Font
  become: true
  unarchive:
    src: /tmp/SpaceMono.zip
    dest: /usr/local/share/fonts/nerd-fonts
    remote_src: yes
