---
- name: Add the Wezterm GPG key
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
  args:
    creates: /etc/apt/keyrings/wezterm-fury.gpg

- name: Add the Wezterm APT repository
  become: true
  ansible.builtin.shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
  args:
    creates: /etc/apt/sources.list.d/wezterm.list

- name: Update APT repositories
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install Wezterm
  become: true
  ansible.builtin.apt:
    name: wezterm
    state: present

- name: Copy wezterm.lua to .config/wezterm/wezterm.lua
  copy:
    src: "{{ wezterm_config }}"
    dest: "{{ home_dir }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
