---
- name: Install updates (Ubuntu)
  become: true
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name:
      - git
      - bat
      - zsh
      - ripgrep
      - fzf
      - eza
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - python3
      - python3-pip
      - i3
      - i3blocks
      - rofi
      - autoconf
      - automake
      - libevent-dev
      - ncurses-dev
      - pkg-config
      - bison
      - g++
      - fcitx5
      - fcitx5-chewing
      - fcitx5-table-extra
      - trash-cli
      - pavucontrol
    state: latest
