---
- name: Pull dotfiles from GitHub repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ home_dir }}/dotfiles"
    accept_hostkey: yes
    key_file: "{{ ssh_key }}"
    force: yes
  delegate_to: localhost
  run_once: true
