---
- name: Get starship install script
  ansible.builtin.get_url:
    url: "{{ starship_install_script_link }}" 
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Install starship with installation script
  become: true
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

- name: Configure Starship
  copy:
    src: "{{ home_dir }}/dotfiles/.config/starship.toml"
    dest: "{{ home_dir }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
