---
- name: Pull Neovim from GitHub repository
  git:
    repo: "{{ nvim_repo }}"
    dest: "{{ home_dir }}/neovim"
    version: stable

- name: Clear CMake cache
  command:
    cmd: rm -r build/
    chdir: "{{ home_dir }}/neovim"
  args:
    removes: "{{ home_dir }}/neovim/build"

- name: Make
  command:
    cmd: make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim"
    chdir: "{{ home_dir }}/neovim"

- name: Install Neovim
  command:
    cmd: make install
    chdir: "{{ home_dir }}/neovim"

- name: Configure Neovim
  copy:
    src: "{{ home_dir }}/dotfiles/.config/nvim"
    dest: "{{ home_dir }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
